### ISSUE TITLE
opening TWS from macro requires path

### ISSUE THREAD

**Issue by LWollatz** [fiji/Trainable_Segmentation#11]
When trying to open the TWS using a macro, following bug occurs:
macro recorder produces:
`path=[Ljava.lang.String;@45141235`
as the last argument (after 'open' and 'inputfile')
Both 'open' and 'inputfile' take the same value (path + filename of the image file to open).
When trying to execute the macro command, following error occurs:
**'path' is required but unset.**
this goes not only for the originally recorded command, but also if the last argument is modified to equal the full file-path or the path excluding the filename.
(issue also found by others: http://stackoverflow.com/questions/30865418/use-weka-from-imagej-macro-path-is-required-but-unset)

**Comment by iarganda** [comment]
Hello @LWollatz 

As @imagejan nicely explained on his answer in stackoverflow *the Trainable Weka Segmentation plugin doesn't adhere to the macro recording conventions of ImageJ, mainly because of its complex structure.*

*However, the correct way to interact with the plugin by macro scripting is described extensively in its [documentation on the Fiji wiki](http://fiji.sc/Trainable_Weka_Segmentation#Macro_language_compatibility). In summary, you need to something like:*
```java
open("C:\\input\\test.tif"); // open your file
run("Trainable Weka Segmentation"); // then start the plugin

call("trainableSegmentation.Weka_Segmentation.loadClassifier", "C:\\path\\to\\your\\classifier.model");

call("trainableSegmentation.Weka_Segmentation.getProbability");
```

In any case, I strongly recommend using any type of scripting language instead of a macro. There is a [scripting documentation page in the wiki](http://fiji.sc/Scripting_the_Trainable_Segmentation).
