### ISSUE TITLE
Out of date documentation

### ISSUE THREAD

**Issue by LWollatz** [fiji/Trainable_Segmentation#16]
The documentation on Fiji (http://fiji.sc/Trainable_Weka_Segmentation) is out of date. I worked through the filter implementations and am happy to provide an update but I am not sure who is maintaining it. There are some things that I noticed from comparing documentation and implementation that might require minor changes in the code:
1. The Sobel filter as well as the Hessian are applied for Gaussian blurs as described in the documentation, but also for the original image prior to smoothing if e.g. ```sigmamin == 1```. Is this intended?
2. The Gamma-normalized square eigenvalue difference is calculated for t=1^(3/4) this means t=1. Unless there are plans to change it in future, there is no need to calculate ```final double t = Math.pow(1, 0.75);``` in the code ;-)
3. Bilateral Filter is evaluated for spatial radius of 5 and 10 only, not for 20! ```for(double i = 5; i < 20; i *= 2)``` This looks like its not intentional.

**Comment by ctrueden** [comment]
In general, it is a wiki, so if you see wrong or out of date documentation, you are warmly encouraged to fix it.

The maintainer of TWS is @iarganda. He is awesomely helpful and responsive, so maybe he'll just go ahead and make the changes; I don't know. But you certainly don't have to wait for him to fix the problems.

**Comment by LWollatz** [comment]
Happy to work on the documentation myself, just couldn't find an "edit" button... I will look harder :-)
Also might look into working on the code but I know iarganda is very active and probably will just edit these few lines before I even got around pulling the code :-)

**Comment by iarganda** [comment]
Hello @LWollatz 
Thanks for commenting on all of these issues. Let me go through them:

*1. The Sobel filter as well as the Hessian are applied for Gaussian blurs as described in the documentation, but also for the original image prior to smoothing if e.g. sigmamin == 1. Is this intended?*

Yes, this is intended. When the sigma is 1, we use a circular filter kernel of radius 1, so it is different from applying directly the Sobel filter or the Hessian features to the original image.

*2. The Gamma-normalized square eigenvalue difference is calculated for t=1^(3/4) this means t=1. Unless there are plans to change it in future, there is no need to calculate final double t = Math.pow(1, 0.75); in the code ;-)*

Right! I should update that, of course. I guess it only made sense when exploring the different values of t.

*3. Bilateral Filter is evaluated for spatial radius of 5 and 10 only, not for 20! for(double i = 5; i < 20; i *= 2) This looks like its not intentional.*

Right again. That should be changed in the documentation. Thanks!

**Comment by LWollatz** [comment]
I changed the discrepancies I found in the documentation. 
I will have a look at the Hessian and Sobel filter again, to see if the documentation requires any update/ mentioning of this special case or not.

**Comment by iarganda** [comment]
That's great, thank you very much!
